### ISSUE TITLE
Error Code 100 on Updating Doc?

### ISSUE THREAD

**Issue by ghost** [popojargo/PHP-on-Couch#4]
For some reason I am getting the following error when trying to update my doc. Does anyone know what this means?

> data: "ERROR: Continue (PUT /**database**/**id** []) (100)<br>↵"

	foreach($items as $item)
	{
		$id = $item['id'];

		//document fetching by ID
		$find_item = $userClient->getDoc($id);

		$find_item->folder_id = $new_folder_id;

		try { $userClient->storeDoc($find_item); } 
		catch (Exception $e) { 
			echo "ERROR: ".$e->getMessage()." (".$e->getCode().")<br>\n";
		}
	}

**Comment by popojargo** [comment]
@bgold0  I'll take a look at this. Do you have any issue if you do the same request using cURL? And which version of CouchDB are you using?

**Comment by popojargo** [comment]
@bgold0 Does this solve your problem : https://github.com/popojargo/PHP-on-Couch/commit/0ecda9625028b58e8617e2f6bac82095b4d3830d

**Comment by ghost** [comment]
@popojargo yup! Looks like that commit solved the issue! You rock. Thanks for such a fast reply man saved me so much time.

Care to explain what that issue meant?

**Comment by popojargo** [comment]
@bgold0  Don't close this issue, I will close it when the fix will me on the master branch.
