### ISSUE TITLE
Using library in a function

### ISSUE THREAD

**Issue by ghost** [popojargo/PHP-on-Couch#5]
I know this is typical php knowledge, but maybe it could help people like me. This is not specifically an issue so my apologizes if I should of just stackoverflow'd this.

But is there an easy way to use this in a function?

This is basically what I have but I get the following error:

> <b>Fatal error</b>:  Class 'CouchDocument' not found in....

    use PHPOnCouch\Couch;
    use PHPOnCouch\CouchAdmin;
    use PHPOnCouch\CouchClient;

	function make_doc($db, $final_array) {
		$userClient = new CouchClient("https://user:pass@databaseurl.com, $db);

		$doc = new CouchDocument($userClient);
		$doc->set($final_array);
		return $doc->id();
	}

    $new_id = make_doc("mydb", array("something" => "else"));

**Comment by popojargo** [comment]
You need to use an autoloader to load the classes. See, in PHP, the **use** key is only assigning a name to a class path. For example, when you do `use PHPOnCouch\Couch;`, it maps this path to `CouchClient`. 

In your case, you probably have no autoloader. If you installed the library through composer, you can use their autoloader to load the classes.

If you use composer, simply require the autoload file : `require 'vendor/autoload.php`.

**Comment by ghost** [comment]
Sorry @popojargo, i do have composer autoloader as the first thing. it works fine outside of the function, just not inside it.

**Comment by popojargo** [comment]
@bgold0  Then can you send me the complete error log?

**Comment by popojargo** [comment]
You need to add the use for *PHPOnCouch\CouchDocument* Whenever you need a class from this library, you need to "import it" via the **use** keyword.

**Comment by bgold0** [comment]
This is the full code/error. If I do all of this outside the function, it works fine. Sorry if I'm not following you're advice.

	require_once("vendor/autoload.php");
	use PHPOnCouch\Couch;
    use PHPOnCouch\CouchAdmin;
    use PHPOnCouch\CouchClient;

    function make_doc($db, $final_array) {
		$userClient = new CouchClient("https://user:pass@databaseurl.com, $db);

		$doc = new CouchDocument($userClient);
		$doc->set($final_array);
		return $doc->id();
	}

	$new_id = make_doc("mydb", array("something" => "else"));



> <b>Fatal error</b>:  Class 'CouchDocument' not found in <b>/path/page.php</b> on line <b>10</b><br />

**Line 10 is** `$doc = new CouchDocument($userClient);`

**Comment by popojargo** [comment]
@bgold0 See my updated answer before yours

**Comment by ghost** [comment]
Wow, that was incredibly stupid error. My apologies. Thanks for the help man, sometimes just gotta talk it out.

**Comment by popojargo** [comment]
@bgold0 If you feel that the documentation was unclear, you can update it and send me a pull request.

**Comment by ghost** [comment]
Not at all, I'm heavily using your library throughout a giant project and your documentation has been real solid. I was including php files and the CouchDocument class was not in the file that defined the function. it was an oversite on my part.
