### ISSUE TITLE
PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by ghost** [popojargo/PHP-on-Couch#6]
Just letting you know I receive this in my error logs.

> 17:20:58.042
PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /.../vendor/popojargo/php-on-couch/src/Couch.php on line 546

**Comment by popojargo** [comment]
@bgold0 Seems like it's only up to you to change your configuration. http://stackoverflow.com/questions/6352927/curlopt-followlocation-cannot-be-activated

**Comment by ghost** [comment]
Hmm okay. I am using google app engine and can't change my php.ini file. I'll try and figure it out.

If I set CURLOPT_FOLLOWLOCATION to false in your code, will that break something?

**Comment by popojargo** [comment]
@bgold0 I seriously have no idea.

**Comment by popojargo** [comment]
@bgold0 After few sites reading, I found out that this is not a good idea to disable so It will stay like this. I'm closing the issue unless you have any good reason to keep it open.
