### ISSUE TITLE
Sorting Views by attribute for pagination

### ISSUE THREAD

**Issue by ghost** [popojargo/PHP-on-Couch#8]
Let's say I have 1000 items like this:

    { "_id": "12345", "type": "item", "name": "whatever", "timestamp": 1481659373 }

And I have a view that grabs only a specific type.

**View**
    
    function (doc) { emit([doc.type], doc._id); }

**PHP**

    $get_items = $userClient
        ->startkey(['item'])
        ->endkey(['item'])
        ->include_docs(TRUE)
        ->asArray()
        ->getView('filters','type');

I know I can use `offset` and `limit` for pagination. But I'm trying to grab the most recent timestamps first in descending order. I see that there is a `descending` option but it looks like you only set it to true so I'm not sure of its functionality. Do you have any recommendations?

P.S. - Sorry this is not technically a bug. I'll be happy to close this if this is not the sort of thing I should be fielding here.

**Comment by popojargo** [comment]
You're right, this is not the place to ask this kind of question. I just added a link at the bottom of the README, feel free to join the chat room and ask your questions there. Otherway, ask a question on StackOverflow since it's related to CouchDB, not the library.
